---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 10-demo-kustomize-oci-bb-app
  namespace: flux-system
spec:
  interval: 10s
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: 10-demo-source-oci-bb-app
  targetNamespace: 10-demo

