---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: 7-demo-source-oci-bb-app-7-7-0
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 7-demo-3671c05
  secretRef:
    name: ghcr-auth
  url: oci://ghcr.io/sid-demo/bb-app-7.7.0

