---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-security-kustomize-git-sealed-secrets
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infrastructure/bitnami-sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-security-source-git-sealed-secrets

