---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infra-security-source-git-sealed-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: 9-demo
  url: https://github.com/sid-demo/bb-app-source

