---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: notification-provider-slack
  namespace: flux-system
spec:
  address: https://slack.com/api/chat.postMessage
  channel: general
  secretRef:
    name: slack-bot-token
  type: slack
  username: flux-bot

