apiVersion: v1
kind: Service
metadata:
  labels:
    app: block-buster
  name: block-buster-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort:
  selector:
    app: block-buster
  type: NodePort